'use client';
import {useCallback,useEffect,useState} from 'react';
import {Activity,ArrowDownRight,ArrowUpRight,ArrowRight,BarChart3,FlaskConical,Layers,Radio,RotateCcw,Play,Pause,ShieldCheck,SlidersHorizontal,Zap,Search,Download,Globe,ChevronRight} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar,PieChart,Pie,Cell,Legend} from 'recharts';
import {request} from '@/lib/api';
import type {Asset,Signal,Scenario,Stats,Stress} from '@/lib/types';

const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
const million=(v:number)=>`₹${(v/1e6).toFixed(2)}M`;
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const colors=['#3478f6','#24b8a5','#9d87e9','#e6a449','#ef7580','#85a1be'];
const pages=[['Overview',Activity],['Risk Feed',Radio],['Event Intelligence',Zap],['Portfolio',Layers],['Stress Testing',FlaskConical],['Scenarios',SlidersHorizontal]] as const;
const badge=(risk:string)=><span className={`badge ${risk.toLowerCase()}`}>{risk}</span>;
function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="panel"><div className="panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
function Chart({data,x,y,color='#3478f6',bar=false}:{data:Record<string,unknown>[];x:string;y:string;color?:string;bar?:boolean}){return <div className="chart"><ResponsiveContainer width="100%" height="100%">{bar?<BarChart data={data}><CartesianGrid stroke="#e9edf3" vertical={false}/><XAxis dataKey={x} tick={{fontSize:11}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:11}} tickLine={false} axisLine={false}/><Tooltip/><Bar dataKey={y} fill={color} radius={[4,4,0,0]}/></BarChart>:<AreaChart data={data}><defs><linearGradient id={`fill${y}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.18}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e9edf3" vertical={false}/><XAxis dataKey={x} tick={{fontSize:11}} tickLine={false} axisLine={false}/><YAxis tick={{fontSize:11}} tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey={y} stroke={color} strokeWidth={2.5} fill={`url(#fill${y})`}/></AreaChart>}</ResponsiveContainer></div>}

export default function Dashboard(){
  const [page,setPage]=useState('Overview');
  const [feed,setFeed]=useState<Signal[]>([]),[assets,setAssets]=useState<Asset[]>([]),[scenarios,setScenarios]=useState<Scenario[]>([]),[stats,setStats]=useState<Stats|null>(null);
  const [selected,setSelected]=useState<Signal|null>(null),[result,setResult]=useState<Stress|null>(null),[health,setHealth]=useState<{sentiment_mode:string;data_mode:string}|null>(null);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[playing,setPlaying]=useState(false),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[sourceFilter,setSourceFilter]=useState('all'),[intensity,setIntensity]=useState(1),[text,setText]=useState(''),[source,setSource]=useState('news'),[updated,setUpdated]=useState('');
  const refresh=useCallback(async()=>{try{const [f,p,s,t,h]=await Promise.all([request<Signal[]>('/api/risk-feed'),request<{assets:Asset[]}>('/api/portfolio'),request<Scenario[]>('/api/scenarios'),request<Stats>('/api/statistics'),request<{sentiment_mode:string;data_mode:string}>('/api/health')]);setFeed(f);setAssets(p.assets);setScenarios(s);setStats(t);setHealth(h);setUpdated(new Date().toLocaleTimeString());setError('');setSelected(old=>old?f.find(a=>a.id===old.id)||old:f[0]||null);}catch(e){setError(`Backend unavailable. ${(e as Error).message}. Start the backend, then retry.`);}},[]);
  useEffect(()=>{refresh();const id=setInterval(refresh,5000);return()=>clearInterval(id)},[refresh]);
  const perform=useCallback(async(task:()=>Promise<void>)=>{setBusy(true);setError('');try{await task()}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[]);
  const next=useCallback(async()=>{const signal=await request<Signal&{complete?:boolean}>('/api/demo/next',{});if(signal.complete){setPlaying(false);setNotice('Replay complete. Reset the demo to replay all events.');return;}setSelected(signal);setResult(null);if(signal.stress_recommended){setNotice(`High-impact ${label(signal.event_type)} event · ${signal.impact_score}/10. Synthetic stress test saved automatically.`);}await refresh();},[refresh]);
  useEffect(()=>{if(!playing)return;const id=setInterval(()=>perform(next),7000);return()=>clearInterval(id)},[playing,next,perform]);
  const runStress=async()=>{if(!selected)return;await perform(async()=>{const r=await request<Stress>('/api/stress-test',{signal_id:selected.id,intensity});setResult(r);setPage('Stress Testing');setNotice('Synthetic scenario analysis completed.');});};
  const select=(s:Signal)=>{setSelected(s);setResult(null);setPage('Event Intelligence')};
  const total=assets.reduce((s,a)=>s+a.value,0);
  const allocation=Object.entries(assets.reduce<Record<string,number>>((s,a)=>({...s,[a.asset_type]:(s[a.asset_type]||0)+a.value/1e6}),{})).map(([name,value])=>({name,value}));
  const sectors=Object.entries(assets.reduce<Record<string,number>>((s,a)=>({...s,[a.sector]:(s[a.sector]||0)+a.value/1e6}),{})).map(([sector,value])=>({sector,value}));
  const distribution=Object.entries(feed.reduce<Record<string,number>>((s,a)=>({...s,[label(a.event_type)]:(s[label(a.event_type)]||0)+1}),{})).map(([name,value])=>({name,value}));
  const trend=(stats?.trend||[]).map((s,i)=>({time:`${i+1}`,impact:s.impact_score,sentiment:s.sentiment_score}));
  const filtered=feed.filter(s=>(sourceFilter==='all'||s.source_type===sourceFilter)&&`${s.headline} ${s.event_type} ${s.entities.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const exportData=()=>{const blob=new Blob([JSON.stringify({signals:feed,stress_result:result},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='riskpulse-analysis.json';a.click();URL.revokeObjectURL(url)};
  const feedTable=(rows:Signal[])=><div className="table-wrap"><table><thead><tr><th>Event / source</th><th>Classification</th><th>Sentiment</th><th>Impact</th><th>Risk</th><th/></tr></thead><tbody>{rows.map(s=><tr key={s.id} onClick={()=>select(s)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')select(s)}}><td><strong>{s.headline}</strong><small>{s.source_type==='news'?'NEWS':'SOCIAL'} · {new Date(s.timestamp).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})} · {s.entities.slice(0,2).join(', ')||s.affected_sectors.join(', ')||'No entity match'}</small></td><td><span className="event-tag">{label(s.event_type)}</span></td><td className={s.sentiment_score<0?'negative':'positive'}>{s.sentiment_score>0?'+':''}{s.sentiment_score.toFixed(2)}</td><td><span className="impact-number">{s.impact_score.toFixed(1)}<small>/10</small></span></td><td>{badge(s.risk_level)}</td><td><ChevronRight size={16}/></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No matching signals. Process the next event or analyze text.</div>}</div>;
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><Activity size={24}/></div><div>RiskPulse<span>AI RISK INTELLIGENCE</span></div></div><div className="workspace"><span className="workspace-icon">SP</span><div>Research workspace<small>Hackathon 2026</small></div><ShieldCheck size={16}/></div><div className="nav-label">WORKSPACE</div><nav>{pages.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon size={18}/>{name}{name==='Risk Feed'&&<span className="count">{feed.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="mode-card"><span className="dot"/> DEMO ENVIRONMENT<p>Deterministic synthetic data.<br/>Ready for an offline demo.</p></div><div className="analyst"><div className="avatar">RA</div><div>Risk Analyst<small>Individual submission</small></div></div></div></aside>
    <main><header><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>{page}</strong></div><div className="header-status"><span className={`dot ${error?'offline':''}`}/>{error?'Disconnected':health?'System operational':'Connecting…'}<span className="divider"/><span className="header-date">S&P Global & Crisil · 2026</span></div></header><div className="content"><div className="page-head"><div><div className="eyebrow">FINANCIAL RISK MONITORING</div><h1>{page==='Overview'?'Portfolio risk overview':page}</h1><p>Unstructured intelligence. Explainable exposure. Computed impact.</p></div><div className="actions"><button className="button secondary" onClick={exportData}><Download size={15}/>Export</button><button className="button primary" disabled={busy||!health} onClick={()=>perform(next)}><Zap size={15}/>Next event</button></div></div>
    <div className="control-strip"><div><span className="dot"/><b>{health?.data_mode==='live_news'?'Live news · synthetic portfolio':health?.data_mode==='demo_fallback'?'Demo fallback · live source error':'Synthetic demo feed'}</b><span>{stats?.demo_cursor||0} / {stats?.demo_total||24} source records</span><span className="model-chip">{health?.sentiment_mode==='finbert'?'FinBERT model':'Lexicon fallback'}</span></div><div><span className="last-updated">Updated {updated||'—'}</span><button className="icon-button" aria-label={playing?'Pause replay':'Start replay'} onClick={()=>setPlaying(v=>!v)} disabled={!!error}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><button className="icon-button" aria-label="Reset demo" disabled={busy} onClick={()=>perform(async()=>{setPlaying(false);await request('/api/demo/reset',{});setSelected(null);setResult(null);setNotice('Demo reset to six ordinary records. Next event introduces the geopolitical shock.');await refresh();})}><RotateCcw size={16}/></button></div></div>
    {error&&<div className="alert error">{error}<button onClick={refresh}>Retry connection</button></div>}{notice&&<div className="alert"><Zap size={17}/>{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
    {page==='Overview'&&<><div className="metrics overview-metrics"><div className="metric"><span>Total portfolio value<Layers size={17}/></span><h2>{million(total)}</h2><small>12 synthetic positions · INR</small></div><div className="metric"><span>Current risk score<Activity size={17}/></span><h2>{stats?.average_impact.toFixed(1)||'0.0'}<em>/ 10</em></h2><small>Mean impact across processed signals</small></div><div className="metric"><span>High-impact events<Zap size={17}/></span><h2>{stats?.high_impact_events||0}</h2><small className="negative">Impact ≥ 8 · automatic stress tests</small></div><div className="metric"><span>Negative sentiment<ArrowDownRight size={17}/></span><h2>{stats?.negative_sentiment||0}<em>signals</em></h2><small>Score below −0.15</small></div><div className="metric"><span>Portfolio exposure<ShieldCheck size={17}/></span><h2>{million(Math.max(0,...feed.map(s=>s.exposure.weighted_exposure)))}</h2><small>Largest weighted signal exposure</small></div></div>
    <div className="grid-main"><Card title="Risk signal trend" subtitle="Impact severity across processed records" action={<span className="legend-dot">Impact score</span>}><Chart data={trend} x="time" y="impact"/><div className="chart-foot">Record sequence <span>Business-rule score · 1–10</span></div></Card><Card title="Event distribution" subtitle="Classifications in the active feed"><div className="chart"><ResponsiveContainer><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={4}>{distribution.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend iconType="circle" wrapperStyle={{fontSize:11}}/></PieChart></ResponsiveContainer></div></Card></div>
    <div className="grid-equal"><Card title="Financial sentiment" subtitle="Signed signal score, −1 to +1"><Chart data={trend} x="time" y="sentiment" color="#24b8a5"/></Card><Card title="Sector exposure" subtitle="Synthetic portfolio allocation · INR millions"><Chart data={sectors} x="sector" y="value" bar color="#7898ca"/></Card></div>
    <Card title="Latest risk intelligence" subtitle="Select a signal to inspect its evidence and portfolio exposure" action={<button className="text-button" onClick={()=>setPage('Risk Feed')}>View full feed <ArrowRight size={14}/></button>}>{feedTable(feed.slice(0,5))}</Card></>}
    {page==='Risk Feed'&&<><div className="filter-bar"><div className="search"><Search size={16}/><input placeholder="Search headlines, entities or events" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Source filter" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="all">All sources</option><option value="news">Financial news</option><option value="social">Social posts</option></select><button className="button secondary" disabled={busy} onClick={()=>perform(async()=>{const r=await request<{mode:string;reason?:string}>('/api/ingest/live',{});setNotice(`${label(r.mode)}${r.reason?': '+r.reason:''}`);await refresh();})}><Globe size={15}/>Fetch live news</button></div><Card title="Risk signal feed" subtitle={`${filtered.length} signals · synthetic local news and social posts`}>{feedTable(filtered)}</Card><Card title="Analyze financial text" subtitle="Run new text through the same NLP and exposure pipeline"><textarea placeholder="Paste financial news or a social post…" value={text} onChange={e=>setText(e.target.value)} maxLength={12000}/><div className="form-actions"><select aria-label="Input source" value={source} onChange={e=>setSource(e.target.value)}><option value="news">Financial news</option><option value="social">Social post</option></select><button className="button primary" disabled={busy||text.trim().length<3} onClick={()=>perform(async()=>{const s=await request<Signal>('/api/analyze',{text,source_type:source});select(s);setText('');await refresh();})}>Analyze text <ArrowRight size={15}/></button></div></Card></>}
    {page==='Event Intelligence'&&(selected?<><div className="detail-banner"><div><span className="event-tag">{label(selected.event_type)}</span>{badge(selected.risk_level)}<h2>{selected.headline}</h2><p>{selected.text}</p><small>{selected.source} · {new Date(selected.timestamp).toLocaleString('en-IN')} · {selected.source_type.toUpperCase()}</small></div><button className="button primary" disabled={busy||selected.event_type==='OTHER'} onClick={runStress}><FlaskConical size={17}/>Run stress test</button></div><div className="metrics"><div className="metric"><span>Sentiment score</span><h2 className={selected.sentiment_score<0?'negative':'positive'}>{selected.sentiment_score.toFixed(2)}</h2><small>{selected.sentiment_label}</small></div><div className="metric"><span>Impact severity</span><h2>{selected.impact_score}<em>/ 10</em></h2><small>{selected.stress_recommended?'Automatic stress test triggered':'Below automatic trigger threshold'}</small></div><div className="metric"><span>Evidence strength</span><h2>{(selected.confidence*100).toFixed(0)}<em>%</em></h2><small>Combined evidence; not probability</small></div><div className="metric"><span>Direct portfolio exposure</span><h2>{million(selected.exposure.direct_exposure)}</h2><small>Issuer and sector matches</small></div></div><div className="grid-equal"><Card title="Why this event matters" subtitle="Transparent scoring evidence"><ol className="reasons">{selected.impact_reason.map(r=><li key={r}>{r}</li>)}</ol><div className="exposure-note"><ShieldCheck size={18}/><div><b>{selected.exposure.label}</b><p>{million(selected.exposure.weighted_exposure)} weighted exposure · {million(selected.exposure.high_sensitivity_exposure)} high sensitivity</p></div></div></Card><Card title="Risk engine evidence" subtitle="Model output and business rules stay distinguishable"><dl><dt>Sentiment inference</dt><dd>{selected.sentiment_method}</dd><dt>Sentiment confidence</dt><dd>{selected.sentiment_confidence_kind}</dd><dt>Event classification</dt><dd>TF-IDF similarity + weighted rules</dd><dt>Rule evidence</dt><dd>{selected.classification_evidence.join(', ')||'TF-IDF similarity only'}</dd><dt>Entities</dt><dd>{selected.entities.join(', ')||'No issuer or country match'}</dd><dt>Affected sectors</dt><dd>{selected.affected_sectors.join(', ')||'No sector match'}</dd><dt>Processing latency</dt><dd>{selected.inference_ms.toFixed(1)} ms</dd></dl></Card></div><Card title="Impact score decomposition" subtitle="Base 1 + weighted component contributions; configurable weights"><Chart data={Object.entries(selected.impact_components).map(([factor,points])=>({factor,points}))} x="factor" y="points" bar/></Card></>:<div className="empty">Select an event from the risk feed.</div>)}
    {page==='Portfolio'&&<><div className="portfolio-hero"><div><span>SYNTHETIC WHOLESALE-BANKING PORTFOLIO</span><h2>{money(total)}</h2></div><p>{assets.length} positions<br/>5 asset classes · 6 sectors</p></div><div className="grid-equal"><Card title="Asset allocation" subtitle="Portfolio value in INR millions"><div className="chart"><ResponsiveContainer><PieChart><Pie data={allocation} dataKey="value" nameKey="name" innerRadius={65} outerRadius={95}>{allocation.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/><Legend iconType="circle" wrapperStyle={{fontSize:12}}/></PieChart></ResponsiveContainer></div></Card><Card title="Sector exposure" subtitle="Actual position values, not precomputed outputs"><Chart data={sectors} x="sector" y="value" bar color="#24b8a5"/></Card></div><Card title="Portfolio positions" subtitle="High sensitivity means event sensitivity ≥ 0.70"><div className="table-wrap"><table><thead><tr><th>Asset / issuer</th><th>Type</th><th>Sector</th><th>Value</th><th>Geopolitical</th><th>Credit</th></tr></thead><tbody>{assets.map(a=><tr key={a.asset_id}><td><strong>{a.issuer}</strong><small>{a.asset_id}</small></td><td>{a.asset_type}</td><td>{a.sector}</td><td>{million(a.value)}</td><td>{badge(a.sensitivities.GEOPOLITICAL>=.7?'HIGH':'MEDIUM')} {a.sensitivities.GEOPOLITICAL}</td><td>{a.sensitivities.CREDIT_EVENT}</td></tr>)}</tbody></table></div></Card><Card title="Event sensitivity exposure" subtitle="Sensitivity-weighted value across the full portfolio · INR millions"><Chart data={scenarios.map(s=>({event:label(s.event_type),value:assets.reduce((n,a)=>n+a.value*a.sensitivities[s.event_type],0)/1e6}))} x="event" y="value" bar/></Card></>}
    {page==='Stress Testing'&&<><Card title="Scenario configuration" subtitle="Choose a signal; its classification selects the matching scenario"><div className="stress-form"><label>Risk signal<select value={selected?.id||''} onChange={e=>{setSelected(feed.find(s=>s.id===e.target.value)||null);setResult(null)}}>{feed.map(s=><option key={s.id} value={s.id}>{s.headline} · {s.impact_score}/10</option>)}</select></label><label>Shock multiplier <b>{intensity.toFixed(1)}×</b><input aria-label="Shock multiplier" type="range" min="0.1" max="2" step="0.1" value={intensity} onChange={e=>{setIntensity(Number(e.target.value));setResult(null)}}/></label><button className="button primary" disabled={busy||!selected||selected.event_type==='OTHER'} onClick={runStress}><FlaskConical size={16}/>{busy?'Calculating…':'Run scenario'}</button></div>{selected&&<div className="scenario-inline"><b>{label(selected.event_type)}</b><span>Impact {selected.impact_score}/10</span><span>{selected.stress_recommended?'Automatic trigger: impact ≥ 8':'Manual analyst scenario'}</span></div>}</Card>
    {result?<><div className="assumption"><ShieldCheck size={17}/><b>Synthetic hackathon stress assumptions</b><span>Scenario analysis; no market forecast.</span></div><div className="metrics"><div className="metric"><span>Portfolio before</span><h2>{million(result.portfolio_before)}</h2><small>Baseline asset values</small></div><div className="metric"><span>Portfolio after</span><h2>{million(result.portfolio_after)}</h2><small>Computed scenario repricing</small></div><div className="metric"><span>{result.absolute_loss>=0?'Scenario loss':'Scenario gain'}</span><h2 className={result.absolute_loss>=0?'negative':'positive'}>{million(Math.abs(result.absolute_loss))}</h2><small>Sum of all asset contributions</small></div><div className="metric"><span>Loss percentage</span><h2>{result.loss_percentage.toFixed(2)}<em>%</em></h2><small>Signed loss / baseline value</small></div></div><div className="grid-equal"><Card title="Portfolio before & after" subtitle="Scenario value · INR millions"><Chart data={[{stage:'Before',value:result.portfolio_before/1e6},{stage:'After',value:result.portfolio_after/1e6}]} x="stage" y="value" bar/></Card><Card title="Sector loss contribution" subtitle="Signed scenario losses · INR millions"><Chart data={result.sector_losses.map(s=>({...s,loss:s.loss/1e6}))} x="sector" y="loss" bar color="#e66b76"/></Card></div><Card title="Asset-level losses" subtitle="Signed losses by asset · INR millions"><Chart data={result.assets.map(a=>({asset:a.asset_id,loss:(a.loss||0)/1e6}))} x="asset" y="loss" bar color="#e66b76"/></Card><Card title="Top loss contributors" subtitle="Ordered by computed loss"><div className="table-wrap"><table><thead><tr><th>Issuer / position</th><th>Mapping</th><th>Baseline</th><th>Applied shock</th><th>Loss</th><th>After</th></tr></thead><tbody>{result.top_contributors.map(a=><tr key={a.asset_id}><td><strong>{a.issuer}</strong><small>{a.asset_id} · {a.asset_type}</small></td><td>{a.mapping_reason}</td><td>{million(a.value)}</td><td>{((a.shock||0)*100).toFixed(2)}%</td><td className="negative">{million(a.loss||0)}</td><td>{million(a.after||0)}</td></tr>)}</tbody></table></div><p className="formula">{result.formula}</p></Card></>:<div className="empty stress-empty"><FlaskConical size={34}/><h3>Explore the portfolio impact</h3><p>Run the selected event through a synthetic stress scenario.<br/>Every result comes from asset-level calculations.</p><button className="text-button" disabled={busy} onClick={()=>perform(async()=>{const all=await request<Stress[]>('/api/stress-tests');const r=[...all].reverse().find(r=>r.signal_id===selected?.id);if(r)setResult(r);else setNotice('No saved test for this signal. Run a scenario.');})}>Load saved automatic test <ArrowRight size={15}/></button></div>}
    {selected&&<Card title="Scenario assumptions" subtitle="Shocks before impact, sensitivity and mapping scaling"><dl>{Object.entries(scenarios.find(s=>s.event_type===selected.event_type)?.shocks||{}).map(([k,v])=><div className="assumption-row" key={k}><dt>{k}</dt><dd>{(v*100).toFixed(1)}%</dd></div>)}</dl><p className="formula">Rate shift: {((scenarios.find(s=>s.event_type===selected.event_type)?.rate_change||0)*100).toFixed(1)} percentage points. Bond price response approximates −duration × rate shift.</p></Card>}</>}
    {page==='Scenarios'&&<><div className="assumption"><ShieldCheck size={17}/><b>Synthetic hackathon stress assumptions</b><span>All shocks and sensitivities are illustrative.</span></div><div className="scenario-grid">{scenarios.map(s=><Card key={s.id} title={s.name} subtitle={`Event: ${label(s.event_type)}`}><dl>{Object.entries(s.shocks).map(([k,v])=><div className="assumption-row" key={k}><dt>{k}</dt><dd className={v<0?'negative':'positive'}>{(v*100).toFixed(1)}%</dd></div>)}<div className="assumption-row"><dt>Interest-rate shift</dt><dd>+{(s.rate_change*100).toFixed(1)} pp</dd></div></dl><p className="formula">{s.assumptions}</p></Card>)}</div></>}
    <footer><span><ShieldCheck size={13}/> Synthetic data and stress assumptions. For demonstration and research.</span><span>RiskPulse AI · v1.0</span></footer></div></main></div>
}
