'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {request} from '@/lib/api';
import type {Detail,Graph,GraphNode,Result} from '@/lib/v2-types';
export const money=(n:number)=>`₹${(n/1e6).toFixed(3)}M`;
export const label=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export function Badge({value}:{value:string}){return <span className={`badge ${value.toLowerCase()}`}>{value}</span>}
export function Panel({title,note,children,action}:{title:string;note?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="panel"><div className="panel-head"><div><h3>{title}</h3>{note&&<p>{note}</p>}</div>{action}</div>{children}</section>}
export function Metric({title,value,note}:{title:string;value:string;note:string}){return <div className="metric"><span>{title}</span><h2>{value}</h2><small>{note}</small></div>}
export function Plot({data,x,y,bar=false,color='#3478f6'}:{data:Record<string,unknown>[];x:string;y:string;bar?:boolean;color?:string}){return <div className="chart v2chart"><ResponsiveContainer width="100%" height="100%">{bar?<BarChart data={data} margin={{left:8,right:18,bottom:10}}><CartesianGrid vertical={false} stroke="#e9edf3"/><XAxis dataKey={x} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} width={44} axisLine={false} tickLine={false}/><Tooltip/><Bar isAnimationActive={false} dataKey={y} fill={color} radius={[4,4,0,0]}/></BarChart>:<AreaChart data={data} margin={{left:8,right:18,bottom:10}}><CartesianGrid vertical={false} stroke="#e9edf3"/><XAxis dataKey={x} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} width={44} axisLine={false} tickLine={false}/><Tooltip/><Area isAnimationActive={false} dataKey={y} stroke={color} fill={color} fillOpacity={.09} strokeWidth={2} type="linear"/></AreaChart>}</ResponsiveContainer></div>}
export function Explanation({detail}:{detail:Detail}){return <Panel title="Why did RiskPulse flag this?" note="Deterministic explanation generated from computed fields"><ol className="reasons">{detail.explanation.map((line,i)=><li key={i}>{line}</li>)}</ol></Panel>}
export function Transmission({graph,initialAsset,compact=false}:{graph:Graph;initialAsset?:string;compact?:boolean}){
 const [selected,setSelected]=useState<GraphNode|null>(null);
 useEffect(()=>{setSelected(old=>graph.nodes.find(n=>n.id===(old?.id||`asset:${initialAsset}`))||null)},[graph,initialAsset]);
 const groups=['event','entity','sector','asset','portfolio'],positions=new Map<string,{x:number;y:number}>();
 groups.forEach((type,col)=>{const nodes=graph.nodes.filter(n=>n.type===type);nodes.forEach((n,i)=>positions.set(n.id,{x:20+col*218,y:55+(i+.5)*500/Math.max(nodes.length,1)}))});
 const paths=selected?graph.risk_paths.filter(p=>p.nodes.includes(selected.id)):graph.risk_paths,active=new Set(paths.flatMap(p=>p.nodes));
 return <><div className="map-wrap"><svg className={compact?'transmission compact':'transmission'} viewBox="0 0 1100 590" role="group" aria-label="Computed event to portfolio risk transmission graph">
 {groups.map((t,i)=><text key={t} x={100+i*218} y={25} textAnchor="middle" className="map-heading">{t.toUpperCase()}</text>)}
 {graph.edges.map((e,i)=>{const a=positions.get(e.source)!,b=positions.get(e.target)!,enabled=active.has(e.source)&&active.has(e.target);return <path key={i} d={`M${a.x+174},${a.y} C${a.x+203},${a.y} ${b.x-25},${b.y} ${b.x},${b.y}`} fill="none" stroke={enabled?'#729cbd':'#dce4ee'} strokeOpacity={enabled?.6:.3} strokeWidth={1+e.weight*1.5}><title>{e.meaning}: {e.weight.toFixed(3)}</title></path>})}
 {graph.nodes.map(n=>{const p=positions.get(n.id)!;return <g key={n.id} role="button" tabIndex={0} aria-label={`Inspect ${n.label}`} onClick={()=>setSelected(n)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n)}}} className="graph-node"><rect x={p.x} y={p.y-17} width={174} height={34} rx={5} fill={selected?.id===n.id?'#16334f':n.type==='asset'?'#f4f8fc':'#fff'} stroke={selected?.id===n.id?'#16334f':'#cddbe8'}/><text x={p.x+9} y={p.y+4} fill={selected?.id===n.id?'white':'#314d67'} fontSize={11}>{n.type==='asset'?`${n.label} · ${money(n.value||0)}`:label(n.label).slice(0,25)}</text><title>{n.label} · click for evidence</title></g>})}
 </svg></div><div className="map-footer"><span>{graph.risk_paths.length} unique asset paths</span><b>{graph.total_propagated_risk.toFixed(3)} portfolio risk points</b><span>Weighted exposure {money(graph.exposure.weighted_exposure)}</span></div>
 {selected?<div className="node-detail"><div><span className="eyebrow">SELECTED {selected.type.toUpperCase()}</span><h3>{selected.issuer||selected.label}</h3><p>{selected.mapping_reason||selected.reason||'Select a connected position to inspect its financial assumptions.'}</p></div>{selected.type==='asset'?<dl className="node-values">{[['Asset value',money(selected.value||0)],['Sector',selected.sector],['Sensitivity',(selected.sensitivity||0).toFixed(2)],['Event exposure',money(selected.event_exposure||0)],['Scenario loss',money(selected.scenario_loss||0)],['Portfolio weight',`${((selected.portfolio_weight||0)*100).toFixed(1)}%`]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>:<p>{paths.length} connected asset paths · {money(paths.reduce((s,p)=>s+p.weighted_exposure,0))} weighted exposure</p>}</div>:<p className="formula">Click a node to inspect exposure. Edge thickness encodes mapping, membership, sensitivity or portfolio weight. {graph.units}</p>}</>;
}
export function Attribution({result,cid}:{result:Result;cid:string}){return <><div className="grid-equal"><Panel title="Loss attribution by sector" note="Signed conditional loss · INR millions"><Plot data={result.sector_losses.map(x=>({...x,loss_M:x.loss/1e6}))} x="sector" y="loss_M" bar color="#c16e6e"/></Panel><Panel title="Scenario outcome" note="Reconciled from individual positions"><div className="outcome"><div><span>Portfolio before</span><b>{money(result.portfolio_before)}</b></div><ArrowRight size={24}/><div><span>Portfolio after</span><b>{money(result.portfolio_after)}</b></div></div><div className="loss-callout"><span>Conditional {result.absolute_loss<0?'gain':'loss'}</span><strong>{money(Math.abs(result.absolute_loss))}</strong><small>{result.loss_percentage.toFixed(3)}% signed loss · synthetic assumptions</small></div></Panel></div><Panel title="Top 5 loss contributors" note="Open a position to trace event → entity → sector → asset"><div className="table-wrap"><table><thead><tr><th>Position / issuer</th><th>Sector</th><th>Sensitivity</th><th>Exposure weight</th><th>Scenario loss</th></tr></thead><tbody>{result.top_contributors.map(a=><tr key={a.asset_id}><td><Link href={`/risk-map?event=${cid}&asset=${a.asset_id}`}><strong>{a.asset_id} ↗ {a.issuer}</strong><small>{label(result.event_type)} · {a.asset_type}</small></Link></td><td>{a.sector}</td><td>{a.sensitivity.toFixed(2)}</td><td>{a.mapping_weight.toFixed(2)}</td><td>{money(a.loss)}</td></tr>)}</tbody></table></div><p className="formula">{result.formula}</p></Panel></>}
export function StressLab({detail}:{detail:Detail}){
 const c=detail.cluster,base=detail.result;
 const [scenario,setScenario]=useState('Moderate'),[intensity,setIntensity]=useState(1),[impact,setImpact]=useState(c.raw_impact),[exposure,setExposure]=useState(1),[rate,setRate]=useState(base?.inputs.rate_shock||0),[equity,setEquity]=useState(base?.inputs.equity_shock||0);
 const [result,setResult]=useState(base),[error,setError]=useState(''),[busy,setBusy]=useState(false),[custom,setCustom]=useState(false);
 useEffect(()=>{if(!custom)return;let current=true;setBusy(true);const t=setTimeout(()=>{request<Result>('/api/v2/what-if',{cluster_id:c.id,impact,intensity,exposure_scale:exposure,rate_shock:rate,equity_shock:equity}).then(r=>{if(current){setResult(r);setError('')}}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setBusy(false)})},300);return()=>{current=false;clearTimeout(t)}},[c.id,impact,intensity,exposure,rate,equity,custom]);
 if(!base)return <div className="empty">No synthetic scenario is defined for this event type.</div>;
 const sliders=[['Event impact',impact,setImpact,0,10,.01,'/10'],['Shock intensity',intensity,setIntensity,0,3,.05,'×'],['Exposure assumption',exposure,setExposure,0,2,.05,'×'],['Interest rate shock',rate*100,(v:number)=>setRate(v/100),-10,10,.1,'pp'],['Equity shock',equity*100,(v:number)=>setEquity(v/100),-100,100,1,'%']] as const;
 return <><Panel title="Base · Moderate · Severe" note="Base: zero shocks. Moderate: original assumptions. Severe: 1.75× shocks."><div className="scenario-buttons">{detail.comparison.map(r=><button key={r.name} onClick={()=>{setScenario(r.name!);setResult(r);setIntensity(r.inputs.intensity);setImpact(r.inputs.impact);setExposure(r.inputs.exposure_scale);setRate(r.inputs.rate_shock);setEquity(r.inputs.equity_shock);setCustom(false);setBusy(false)}} className={`scenario-choice ${!custom&&scenario===r.name?'chosen':''}`}><span>{r.name}</span><b>{money(r.portfolio_after)}</b><small>Signed loss {money(r.absolute_loss)}</small></button>)}</div><Plot data={detail.comparison.map(r=>({scenario:r.name,loss_M:r.absolute_loss/1e6}))} x="scenario" y="loss_M" bar/></Panel><Panel title="What if?" note="Change an assumption to recalculate through the same asset-level stress engine."><div className="whatif-controls">{sliders.map(([name,value,set,min,max,step,unit])=><label key={name}><span>{name}<b>{value.toFixed(2)}{unit}</b></span><input type="range" aria-label={name} value={value} min={min} max={max} step={step} onChange={e=>{set(Number(e.target.value));setCustom(true)}}/></label>)}</div><div className="lab-status" role="status">{busy?'Recalculating scenario…':custom?'What-if calculation complete':`${scenario} scenario selected`}{result&&<span>Worst asset: {result.worst_asset.asset_id} · Worst sector: {result.worst_sector.sector}</span>}</div>{error&&<div role="alert" className="alert error">{error}</div>}</Panel>{result&&<div className={busy?'calculating':''}><Attribution result={result} cid={c.id}/></div>}</>;
}


