'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname,useSearchParams} from 'next/navigation';
import {Activity,ArrowRight,Radio,Network,FlaskConical,Layers,History,ShieldAlert,Grid3X3,FileSearch,ChartNoAxesCombined,RotateCcw,Play,Pause,Globe,Zap,Download} from 'lucide-react';
import {request} from '@/lib/api';
import type {Cluster,Dashboard,Detail} from '@/lib/v2-types';
import {money,label,Badge,Panel,Metric,Plot,Explanation,Transmission,StressLab} from './RiskVisuals';
const nav=[['','Overview',Activity],['risk-feed','Signal intelligence',Radio],['risk-map','Risk transmission',Network],['portfolio','Portfolio exposure',Layers],['stress-testing','Stress & what-if',FlaskConical],['timeline','Event timeline',History],['alerts','Alert center',ShieldAlert],['heatmap','Risk heatmap',Grid3X3],['audit','Model audit',FileSearch],['evaluation','Evaluation',ChartNoAxesCombined]] as const;
type Evaluation={baseline:Record<string,unknown>|null;current:Record<string,unknown>|null;note:string};
export default function RiskWorkspace(){
 const search=useSearchParams().toString(),path=usePathname().slice(1),title=nav.find(n=>n[0]===path)?.[1]||'Event intelligence';
 const [data,setData]=useState<Dashboard|null>(null),[detail,setDetail]=useState<Detail|null>(null),[selected,setSelected]=useState(''),[initialAsset,setInitialAsset]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),[mode,setMode]=useState('DEMO MODE'),[model,setModel]=useState('Connecting'),[query,setQuery]=useState(''),[level,setLevel]=useState('ALL'),[input,setInput]=useState(''),[source,setSource]=useState('news'),[evaluation,setEvaluation]=useState<Evaluation|null>(null);
 const selectedRef=useRef(''),detailVersion=useRef(0),operation=useRef(false);
 const refresh=useCallback(async()=>{try{const [d,h]=await Promise.all([request<Dashboard>('/api/v2/dashboard'),request<{sentiment_mode:string}>('/api/health')]);if(path==='evaluation')setEvaluation(await request<Evaluation>('/api/v2/evaluation'));setData(d);setModel(h.sentiment_mode);setError('');const id=selectedRef.current;if(d.clusters.some(c=>c.id===id)){const version=++detailVersion.current;const next=await request<Detail>(`/api/v2/clusters/${id}`);if(version===detailVersion.current)setDetail(next)}else{setDetail(d.priority);setSelected(d.priority?.cluster.id||'');selectedRef.current=d.priority?.cluster.id||''}}catch(e){setError(`Connection unavailable. ${(e as Error).message}`)}},[path]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);selectedRef.current=p.get('event')||'';setSelected(selectedRef.current);setInitialAsset(p.get('asset')||'');refresh();const t=setInterval(refresh,7000);return()=>clearInterval(t)},[refresh,path,search]);
 const select=async(id:string)=>{selectedRef.current=id;setSelected(id);setDetail(null);const v=++detailVersion.current;try{const d=await request<Detail>(`/api/v2/clusters/${id}`);if(v===detailVersion.current)setDetail(d)}catch(e){setError((e as Error).message)}};
 const perform=useCallback(async(route:string,body:unknown={})=>{if(operation.current)return;operation.current=true;setBusy(true);try{const r=await request<Record<string,unknown>>(route,body);if(r.complete){setPlaying(false);setNotice('Replay complete. Reset to replay.')}else if(route.includes('reset')){selectedRef.current='';setMode('DEMO MODE');setNotice('Reset complete. Next event introduces the geopolitical shock.')}else if(route.includes('live')){setMode(r.mode==='live_news'?'LIVE NEWS · SYNTHETIC SOCIAL':'DEMO FALLBACK');setNotice(r.mode==='live_news'?'Live news ingested. Social data remains synthetic.':`Demo fallback: ${r.reason}`);selectedRef.current=''}else{selectedRef.current='';setNotice('Signal processed. Fusion, exposure and audit history updated.')}await refresh()}catch(e){setPlaying(false);setError((e as Error).message)}finally{operation.current=false;setBusy(false)}},[refresh,path,search]);
 useEffect(()=>{if(!playing)return;const t=setInterval(()=>perform('/api/demo/next'),7000);return()=>clearInterval(t)},[playing,perform]);
 const c=detail?.cluster,filtered=(data?.clusters||[]).filter(c=>(level==='ALL'||c.risk_level===level)&&`${c.headline} ${c.event_type} ${c.companies.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const exportAudit=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(detail,null,2)],{type:'application/json'}));a.href=url;a.download='riskpulse-audit.json';a.click();URL.revokeObjectURL(url)};
 const eventTable=(rows:Cluster[])=><div className="table-wrap"><table><thead><tr><th>Event cluster</th><th>Sources</th><th>Impact</th><th>Confidence</th><th>Effective risk</th><th>Exposure</th><th>Inspect</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><strong>{c.headline}</strong><small>{label(c.event_type)} · {c.affected_sectors.join(', ')||'No sector match'}</small></td><td>{c.source_count}<small>{c.observation_count} observations</small></td><td>{c.raw_impact.toFixed(2)}</td><td>{(c.confidence*100).toFixed(1)}%</td><td><Badge value={c.risk_level}/><small>{c.effective_risk.toFixed(2)} / 10</small></td><td>{money(c.weighted_exposure||0)}</td><td><Link className="text-button" href={`/risk-feed?event=${c.id}`}>Inspect</Link><Link className="text-button" href={`/risk-map?event=${c.id}`}>Trace ↗</Link></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No matching events. Adjust the filter or ingest a signal.</div>}</div>;
 return <div className="shell v2"><aside className="sidebar"><Link className="brand" href="/"><div className="brand-icon"><Activity size={23}/></div><div>RiskPulse<span>PORTFOLIO INTELLIGENCE</span></div></Link><div className="workspace"><span className="workspace-icon">V2</span><div>Risk analyst workspace<small>Wholesale banking · INR</small></div></div><nav>{nav.map(([route,name,Icon])=><Link key={route} className={path===route?'active':''} href={`/${route}`} title={name}><Icon size={17}/><span>{name}</span></Link>)}</nav><div className="sidebar-bottom"><div className="mode-card"><span className="dot"/>{mode}<p>Synthetic portfolio<br/>Prototype risk model</p></div><Link className="legacy-link" href="/legacy">Open preserved V1 workspace ↗</Link></div></aside><main><header><div className="breadcrumb">Risk operations <ArrowRight size={12}/><strong>{title}</strong></div><div className="header-status"><span className={`dot ${error?'offline':''}`}/>{error?'Connection interrupted':model==='Connecting'?'Connecting':`Local model · ${model}`}<span className="header-date">Decision support prototype</span></div></header><div className="content"><div className="page-head"><div><div className="eyebrow">SIGNAL → INTELLIGENCE → EXPOSURE → STRESS → IMPACT</div><h1>{path==='risk-map'?'Risk transmission map':path===''?'Portfolio risk command center':title}</h1><p>Trace every decision from its source to the portfolio.</p></div><div className="actions"><button className="button secondary" disabled={busy} onClick={()=>{setPlaying(false);perform('/api/demo/reset')}}><RotateCcw size={14}/>Reset</button><button className="button primary" disabled={busy} onClick={()=>perform('/api/demo/next')}><Zap size={14}/>{busy?'Processing…':'Next event'}</button></div></div><div className="control-strip"><div><span className="dot"/><b>{mode}</b><span>{data?.observation_count||0} observations → {data?.clusters.length||0} unique events</span><span className="model-chip">{data?.clock||'Awaiting clock'}</span></div><div><button className="icon-button" aria-label={playing?'Pause replay':'Start replay'} disabled={busy||!!error} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><button className="button secondary" disabled={busy} onClick={()=>{setPlaying(false);perform('/api/ingest/live')}}><Globe size={13}/>Fetch live news</button></div></div>
 {error&&<div className="alert error" role="alert">{error}<button onClick={refresh}>Retry connection</button></div>}{notice&&<div className="alert" role="status">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
 {!data?<div className="empty" role="status">{error?'Start the backend, then retry.':'Loading portfolio intelligence…'}</div>:<>
 {path===''&&<><div className="executive"><div><span className="eyebrow">RISK PULSE</span><h2>{data.summary}</h2><p>Priority event: {data.priority?.cluster.headline||'Awaiting signals'}</p></div><Link className="button secondary" href="/alerts">Review alerts <ArrowRight size={14}/></Link></div><div className="metrics"><Metric title="Portfolio value" value={money(data.portfolio_value)} note={`${data.assets.length} synthetic positions`}/><Metric title="Current risk" value={`${data.current_risk.toFixed(2)} / 10`} note="Highest confidence-adjusted event risk"/><Metric title="High-impact events" value={`${data.high_impact_events}`} note="Unique clusters with raw impact ≥ 8"/><Metric title="Estimated stress loss" value={money(data.priority?.result?.absolute_loss||0)} note="Priority event · moderate conditional scenario"/></div><Panel title="Live signal feed" note="Copied observations are collapsed before prioritization" action={<Link className="text-button" href="/risk-feed">All events →</Link>}>{eventTable(data.clusters.slice(0,4))}</Panel>{detail&&<Panel title="Where the risk goes" note={`${label(detail.cluster.event_type)} · actual portfolio transmission paths`} action={<Link className="text-button" href={`/risk-map?event=${detail.cluster.id}`}>Inspect risk map →</Link>}><Transmission graph={detail.graph} compact/></Panel>}<div className="grid-equal"><Panel title="Portfolio exposure" note="Position value by sector · INR millions"><Plot data={data.heatmap.sectors.map(sector=>({sector,value_M:data.assets.filter(a=>a.sector===sector).reduce((s,a)=>s+a.value,0)/1e6}))} x="sector" y="value_M" bar/></Panel><Panel title="Recent stress tests" note="Saved V1 calculations retain the original demo contract">{data.recent_tests.length?<div className="recent-tests">{data.recent_tests.map((r,i)=><div key={i}><span>{label(r.event_type)}<small>{r.signal_id}</small></span><b>{money(r.absolute_loss)}</b></div>)}</div>:<div className="empty">No tests saved. Process a high-impact event.</div>}</Panel></div></>}
 {['risk-map','risk-feed','stress-testing','audit','portfolio'].includes(path)&&<div className="event-select"><label htmlFor="event-choice">Active event</label><select id="event-choice" value={selected} onChange={e=>select(e.target.value)}>{data.clusters.map(c=><option key={c.id} value={c.id}>{c.headline}</option>)}</select>{c&&<Badge value={c.risk_level}/>}</div>}
 {['risk-feed','alerts'].includes(path)&&<><div className="filter-bar"><input aria-label="Search events" className="search" placeholder="Search event, issuer or classification…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter risk level" value={level} onChange={e=>setLevel(e.target.value)}>{['ALL','CRITICAL','HIGH','MEDIUM','LOW'].map(x=><option key={x}>{x}</option>)}</select></div><Panel title={path==='alerts'?'Current risk alerts':'Fused event intelligence'} note="Internal thresholds: Low < 3 · Medium ≥ 3 · High ≥ 6 · Critical ≥ 8">{eventTable(filtered)}</Panel></>}
 {['risk-map','risk-feed','audit','portfolio','stress-testing'].includes(path)&&!detail&&<div className="empty" role="status">{data.clusters.length?'Loading selected event…':'No events available. Process the next event.'}</div>}
 {path==='risk-feed'&&<><Panel title="Analyze a source observation" note="Manual input uses the current time; recency switches to wall time."><textarea aria-label="Source text" placeholder="Paste financial news or a social observation…" value={input} onChange={e=>setInput(e.target.value)}/><div className="form-actions"><select aria-label="Source type" value={source} onChange={e=>setSource(e.target.value)}><option value="news">Financial news</option><option value="social">Social post</option></select><button className="button primary" disabled={busy||input.trim().length<3} onClick={()=>perform('/api/analyze',{text:input,source_type:source,source:'Manual analyst input'})}>Analyze observation</button></div></Panel>{detail&&<><Panel title="Why this event matters" note={detail.cluster.headline}><div className="metrics inner-metrics"><Metric title="Raw impact" value={detail.cluster.raw_impact.toFixed(2)} note="Severity business score / 10"/><Metric title="Evidence confidence" value={`${(detail.cluster.confidence*100).toFixed(1)}%`} note="Heuristic; not probability"/><Metric title="Recency factor" value={detail.cluster.recency_factor.toFixed(3)} note={`${data.config.half_life_hours} hour half-life`}/><Metric title="Adjusted impact" value={detail.cluster.adjusted_impact.toFixed(2)} note="Raw impact × recency"/></div><dl className="intelligence-grid"><div><dt>Source reliability</dt><dd>{detail.cluster.source_reliability.toFixed(2)}</dd></div><div><dt>Source agreement</dt><dd>{(detail.cluster.source_agreement*100).toFixed(1)}%</dd></div><div><dt>Sources / distinct texts / copies</dt><dd>{detail.cluster.source_count} / {detail.cluster.distinct_evidence_count} / {detail.cluster.duplicate_count}</dd></div><div><dt>Who is affected</dt><dd>{detail.cluster.companies.join(', ')||detail.cluster.affected_sectors.join(', ')||'No direct match'}</dd></div><div><dt>Weighted portfolio exposure</dt><dd>{money(detail.graph.exposure.weighted_exposure)}</dd></div><div><dt>Conditional scenario loss</dt><dd>{money(detail.result?.absolute_loss||0)}</dd></div></dl><p className="formula">{detail.cluster.independence_note}</p></Panel><Explanation detail={detail}/></>}</>}
 {path==='risk-map'&&detail&&<><div className="metrics"><Metric title="Direct exposure" value={money(detail.graph.exposure.direct_exposure)} note="Issuer and sector matches"/><Metric title="Weighted exposure" value={money(detail.graph.exposure.weighted_exposure)} note="Includes systemic spillover"/><Metric title="Propagated risk" value={detail.graph.total_propagated_risk.toFixed(3)} note="Portfolio risk points"/><Metric title="Moderate scenario loss" value={money(detail.result?.absolute_loss||0)} note="Conditional synthetic result"/></div><Panel title={label(detail.cluster.event_type)} note={detail.cluster.headline}><Transmission graph={detail.graph} initialAsset={initialAsset}/></Panel><Explanation detail={detail}/><Panel title="Transmission ledger" note="Exactly one path per position"><div className="table-wrap"><table><thead><tr><th>Asset</th><th>Mapping reason</th><th>Edge weights</th><th>Risk points</th><th>Weighted exposure</th></tr></thead><tbody>{detail.graph.risk_paths.map(p=><tr key={p.asset_id}><td>{p.asset_id}</td><td>{p.reason}</td><td>{p.weights.map(w=>w.toFixed(2)).join(' × ')}</td><td>{p.propagated_risk.toFixed(4)}</td><td>{money(p.weighted_exposure)}</td></tr>)}</tbody></table></div><p className="formula">{detail.graph.formula}</p></Panel></>}
 {path==='stress-testing'&&detail&&<StressLab key={`${detail.cluster.id}:${detail.cluster.observation_count}`} detail={detail}/>}
 {path==='portfolio'&&detail&&<><Panel title="Portfolio positions & event exposure" note="Synthetic wholesale-banking assets · sensitivity depends on the selected event"><div className="table-wrap"><table><thead><tr><th>Position / issuer</th><th>Asset class</th><th>Sector</th><th>Value</th><th>Event sensitivity</th><th>Portfolio weight</th></tr></thead><tbody>{data.assets.map(a=><tr key={a.asset_id}><td><Link href={`/risk-map?event=${detail.cluster.id}&asset=${a.asset_id}`}><strong>{a.asset_id} · {a.issuer}</strong></Link></td><td>{a.asset_type}</td><td>{a.sector}</td><td>{money(a.value)}</td><td>{a.sensitivities[detail.cluster.event_type]||0}</td><td>{(100*a.value/data.portfolio_value).toFixed(1)}%</td></tr>)}</tbody></table></div></Panel><Explanation detail={detail}/></>}
 {path==='timeline'&&<><div className="grid-equal">{[['risk_score','Risk score over time'],['sentiment','Event sentiment over time'],['high_impact_events','Unique high-impact events'],['loss_M','Arrival-event scenario loss · INR M']].map(([key,name])=><Panel key={key} title={name} note="Persisted arrival snapshots · observation sequence"><Plot data={data.history.map(h=>({...h,loss_M:h.portfolio_loss/1e6}))} x="sequence" y={key}/></Panel>)}</div><Panel title="Event timeline" note="Actual observations and computed threshold crossings"><div className="table-wrap"><table><thead><tr><th>Sequence / replay time</th><th>Event / transition</th><th>Sentiment</th><th>Impact</th><th>Sources / sector</th><th>Scenario loss</th></tr></thead><tbody>{[...data.history].reverse().map(h=><tr key={h.id}><td>#{h.sequence}<small>{new Date(h.timestamp).toLocaleString()}</small></td><td><Link href={`/risk-map?event=${h.cluster_id}`}><strong>{h.headline}</strong></Link><small>{h.transitions.join(' → ')}</small></td><td>{h.sentiment.toFixed(3)}</td><td>{h.impact.toFixed(2)}</td><td>{h.source_count}<small>{h.sectors.join(', ')}</small></td><td>{money(h.portfolio_loss)}</td></tr>)}</tbody></table>{!data.history.length&&<div className="empty">No V2 history yet. Reset and replay.</div>}</div></Panel></>}
 {path==='heatmap'&&<Panel title="Sector × event sensitivity" note={data.heatmap.method}><div className="table-wrap"><table className="heatmap"><thead><tr><th>Sector</th>{data.heatmap.events.map(e=><th key={e}>{label(e)}</th>)}</tr></thead><tbody>{data.heatmap.sectors.map(s=><tr key={s}><th>{s}</th>{data.heatmap.events.map(e=>{const cell=data.heatmap.cells.find(c=>c.sector===s&&c.event===e)!;return <td key={e}><div style={{background:`rgba(45,104,149,${.05+cell.score*.055})`}}><b>{cell.score.toFixed(1)}</b><small>{money(cell.sensitivity_weighted_exposure)}</small></div></td>})}</tr>)}</tbody></table></div><p className="formula">Scale 0–10. Configured structural sensitivities, not predictions of market moves.</p></Panel>}
 {path==='audit'&&detail&&<><Panel title="Signal-to-decision audit" note="Model evidence, assumptions and reconciled valuation" action={<button className="button secondary" onClick={exportAudit}><Download size={14}/>Export JSON</button>}><div className="audit-body">{detail.cluster.members?.map((m,i)=><details key={i} open={i===0}><summary>Observation {i+1} · {String(m.source_type)} · {String(m.source)}</summary><p>{String(m.text)}</p><pre>{JSON.stringify(m,null,2)}</pre></details>)}<details open><summary>Fusion, credibility and recency</summary><pre>{JSON.stringify(Object.fromEntries(Object.entries(detail.cluster).filter(([k])=>!['members','text'].includes(k))),null,2)}</pre></details><details><summary>Risk paths and exposure</summary><pre>{JSON.stringify(detail.graph,null,2)}</pre></details><details><summary>Stress scenario and final result</summary><pre>{JSON.stringify(detail.result,null,2)}</pre></details></div></Panel><Explanation detail={detail}/></>}
 {path==='evaluation'&&<Panel title="Measured diagnostics: V1 → V2" note={evaluation?.note||'Loading measured results…'}>{evaluation?<div className="audit-body"><div className="alert">24 synthetic author-labelled records, including paired copies. No claim of real-world predictive accuracy.</div><div className="table-wrap"><table><thead><tr><th>Metric</th><th>V1 saved baseline</th><th>V2 measured</th></tr></thead><tbody>{[['records_processed','Records'],['event_classification_accuracy','Event-label agreement'],['sentiment_label_agreement','Sentiment-label agreement'],['average_pipeline_latency_ms','Mean NLP pipeline (ms)'],['average_stress_ms_100_runs','Mean stress calculation (ms)']].map(([key,name])=><tr key={key}><td>{name}</td><td>{formatMetric(evaluation.baseline?.[key],key)}</td><td>{formatMetric(evaluation.current?.[key],key)}</td></tr>)}</tbody></table></div><h3>Controlled sequential vs batched inference</h3><pre>{evaluation.current?JSON.stringify(evaluation.current.benchmark,null,2):'Not measured yet. Run scripts/evaluate_v2.py.'}</pre><p>{String(evaluation.current?.caveats||'')}</p></div>:<div className="empty">{error?'Evaluation unavailable. Retry the connection.':'Loading measured diagnostics…'}</div>}</Panel>}
 </>}
 <footer><span>SYNTHETIC DATA · SYNTHETIC STRESS ASSUMPTIONS · PROTOTYPE RISK MODEL</span><span>RiskPulse AI · v2.0</span></footer></div></main></div>;
}
function formatMetric(v:unknown,key:string){if(typeof v!=='number')return 'Not measured';return key.includes('agreement')||key.includes('accuracy')?`${(v*100).toFixed(2)}%`:v.toFixed(key==='records_processed'?0:3)}



