export interface Cluster {weighted_exposure:number;id:string;headline:string;text:string;event_type:string;raw_impact:number;impact_score:number;recency_factor:number;adjusted_impact:number;confidence:number;effective_risk:number;risk_level:string;sentiment_score:number;source_count:number;observation_count:number;distinct_evidence_count:number;duplicate_count:number;source_agreement:number;source_reliability:number;affected_sectors:string[];companies:string[];timestamp:string;classification_explanation:string;independence_note:string;members?:Record<string,unknown>[]}
export interface Position {asset_id:string;issuer:string;sector:string;asset_type:string;value:number;sensitivities:Record<string,number>;loss:number;after:number;sensitivity:number;mapping_weight:number;portfolio_weight:number;mapping_reason:string}
export interface Result {name?:string;signal_id:string;event_type:string;portfolio_before:number;portfolio_after:number;absolute_loss:number;loss_percentage:number;assets:Position[];top_contributors:Position[];sector_losses:{sector:string;loss:number}[];worst_asset:Position;worst_sector:{sector:string;loss:number};formula:string;inputs:{impact:number;intensity:number;exposure_scale:number;rate_shock:number;equity_shock:number}}
export interface GraphNode {id:string;type:string;label:string;value?:number;sector?:string;sensitivity?:number;event_exposure?:number;scenario_loss?:number;portfolio_weight?:number;issuer?:string;reason?:string;mapping_reason?:string}
export interface Graph {nodes:GraphNode[];edges:{source:string;target:string;weight:number;meaning:string}[];risk_paths:{asset_id:string;nodes:string[];weights:number[];propagated_risk:number;weighted_exposure:number;scenario_loss:number;reason:string}[];total_propagated_risk:number;formula:string;units:string;exposure:{direct_exposure:number;weighted_exposure:number;high_sensitivity_exposure:number;portfolio_value:number}}
export interface Detail {cluster:Cluster;graph:Graph;result:Result|null;comparison:Result[];explanation:string[]}
export interface History {id:string;sequence:number;timestamp:string;headline:string;sentiment:number;impact:number;event_risk:number;risk_score:number;risk_level:string;source_count:number;sectors:string[];high_impact_events:number;portfolio_loss:number;transitions:string[];cluster_id:string}
export interface Dashboard {clusters:Cluster[];assets:Position[];portfolio_value:number;current_risk:number;high_impact_events:number;observation_count:number;summary:string;priority:Detail|null;as_of:string;clock:string;history:History[];recent_tests:Result[];heatmap:{sectors:string[];events:string[];cells:{sector:string;event:string;score:number;sensitivity_weighted_exposure:number}[];method:string};config:{thresholds:Record<string,number>;half_life_hours:number;designation:string}}

